//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVoting.OtherDBContextModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteCount
    {
        public int SerialNumber { get; set; }
        public Nullable<int> CandidateNo { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> CandidateId { get; set; }
    
        public virtual ElectionCandidate ElectionCandidate { get; set; }
        public virtual CandidateMaster CandidateMaster { get; set; }
    }
}
