//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVoting.UserLoginModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralRequest
    {
        public int RequestID { get; set; }
        public string RequestNumber { get; set; }
        public string RequestArea { get; set; }
        public string Requestedto { get; set; }
        public string RequestReason { get; set; }
        public string RequesterEmail { get; set; }
        public string Requestedby { get; set; }
        public string status { get; set; }
    }
}
