//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVoting.UserLoginModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GovernmentDBContext : DbContext
    {
        public GovernmentDBContext()
            : base("name=GovernmentDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserMarksheetDetail> UserMarksheetDetails { get; set; }
        public virtual DbSet<UserVoterIDDetail> UserVoterIDDetails { get; set; }
        public virtual DbSet<AllAdminsList> AllAdminsLists { get; set; }
        public virtual DbSet<GeneralRequest> GeneralRequests { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetTotalNumberOfMarksheets()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetTotalNumberOfMarksheets");
        }
    
        public virtual ObjectResult<Nullable<int>> GetTotalNumberOfVoters()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetTotalNumberOfVoters");
        }
    
        public virtual ObjectResult<Nullable<int>> TotalRegisteredUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("TotalRegisteredUsers");
        }
    
        public virtual ObjectResult<UserVoterIDDetail> GetAllVotersFromArea(string state)
        {
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserVoterIDDetail>("GetAllVotersFromArea", stateParameter);
        }
    
        public virtual ObjectResult<UserVoterIDDetail> GetAllVotersFromArea(string state, MergeOption mergeOption)
        {
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserVoterIDDetail>("GetAllVotersFromArea", mergeOption, stateParameter);
        }
    }
}
