//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVoting.UserLoginModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        public int ImageID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserLoginDetail UserLoginDetail { get; set; }
    }
}
