//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eVoting.UserLoginModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVoterIDDetail
    {
        public string VoterId { get; set; }
        public string Name { get; set; }
        public string FathersName { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string District { get; set; }
        public string State { get; set; }
    }
}
